# Generated by Django 5.1.2 on 2025-01-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalresource',
            name='image',
            field=models.ImageField(null=True, upload_to='edu'),
        ),
    ]
